document: definition+

?definition: operation_definition | fragment_definition
operation_definition: operation_type NAME? variable_definitions? directives? selection_set
                    | selection_set
operation_type: QUERY | MUTATION | SUBSCRIPTION

selection_set: "{" selection+ "}"
?selection: field | fragment_spread | inline_fragment
field: alias? NAME arguments? directives? selection_set?
alias: NAME ":"
arguments: "(" argument (","? argument)* ")"
argument: NAME ":" value
fragment_spread: "..." NAME directives?
inline_fragment: "..." ON NAME directives? selection_set
fragment_definition: FRAGMENT NAME ON NAME directives? selection_set

variable_definitions: "(" variable_definition (","? variable_definition)* ")"
variable_definition: variable ":" type default_value? directives?
variable: VARIABLE
default_value: "=" value
?type: named_type | list_type | non_null_type
named_type: NAME
list_type: "[" type "]"
non_null_type: named_type "!" | list_type "!"

directives: directive+
directive: "@" NAME arguments?

?value: VARIABLE
      | INT
      | FLOAT
      | ESCAPED_STRING
      | BLOCK_STRING
      | TRUE
      | FALSE
      | NULL
      | enum_value
      | list_value
      | object_value
enum_value: NAME
list_value: "[" value* "]"
object_value: "{" object_field* "}"
object_field: NAME ":" value

QUERY.3: /query\b/
MUTATION.3: /mutation\b/
SUBSCRIPTION.3: /subscription\b/
FRAGMENT.3: /fragment\b/
ON.3: /on\b/
TRUE.3: /true\b/
FALSE.3: /false\b/
NULL.3: /null\b/

VARIABLE: /\$[_A-Za-z][_0-9A-Za-z]*/
NAME: /[_A-Za-z][_0-9A-Za-z]*/
INT: /-?(0|[1-9][0-9]*)/
FLOAT: /-?(0|[1-9][0-9]*)(\.[0-9]+)([eE][+-]?[0-9]+)?|-?(0|[1-9][0-9]*)[eE][+-]?[0-9]+/
BLOCK_STRING: /"""(.|\n)*?"""/

%import common.ESCAPED_STRING
COMMENT: /#[^\n]*/
%ignore COMMENT
%ignore /[ \t\r\n,]+/

